### PR TITLE
Fixes for newer ghidra version

### PR DESCRIPTION
**Pull request by viniciuslrangel**

### CODE REVIEW

**Review by astrelsky — APPROVED** [review]

**Comment by astrelsky** [comment]
@viniciuslrangel may you bump the versions in  `.github/workflows/main.yml`

**Comment by viniciuslrangel** [comment]
How about the RTTI stuff? Can I just disable it while it doesn't build?

**Comment by astrelsky** [comment]
> How about the RTTI stuff? Can I just disable it while it doesn't build?

It can be removed. If you don't want to bother with it I can take care of that, it's up to you.

**Comment by viniciuslrangel** [comment]
Removed it!

**Review by astrelsky — COMMENTED** [review]
[(https://github.com/astrelsky/GhidraOrbis/pull/21/files#diff-7829468e86c1cc5d5133195b5cb48e1ff6c75e3e9203777f6b2e379d9e4882b3L34-R65)](https://github.com/astrelsky/GhidraOrbis/pull/21/files#diff-7829468e86c1cc5d5133195b5cb48e1ff6c75e3e9203777f6b2e379d9e4882b3L34-R65)

I'm very bad at the workflow stuff but I think if you remove these lines here the workflow should run just fine.

**Comment by viniciuslrangel** [comment]
I forgot I could run it in my forked repo to test it. I will make sure it builds

**Comment by viniciuslrangel** [comment]
Done!

**Pull request merged**
